### ISSUE TITLE
Пополнение счета больше кредитного лимита.

### ISSUE THREAD

**Issue by YackovPetrov** [rinat-yar/Team_project_on_the_Java_course_for_testers#3]
# Описание.
Если пополнить счет на сумму больше кредитного лимита, то он пополняется.

# Локация дефекта.
https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/blob/bbbc026a1d5326a69e9765a4b6b8ea2e6efa3a9f/src/main/java/ru/netology/CreditAccount.java#L66

# Шаги воспроизведения.
1. Открыть [командный проект](https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers) в IDEA
2. Создать тест в CreditAccountTest для метода Add в классе CreditAccount
3. Выставить значение переменной initialBalance: 0
4. Выставить значение переменной creditLimit: 5_000
5. Выставить значение переменной rate: 15
6. Выполнить пополнение баланса: account.add(6_000)
7. Провести проверку ожидаемого результата с актуальным
8. Посмотреть на выводы в консоли.

*Ожидаемый результат:* Пополнение не произошло,  Balance = 0.
*Фактический результат:* Пополнение произошло, баланс больше кредитного лимита, Balance = 6_000.

# Скриншот.

![image](https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/assets/128886262/d972075a-63c3-4b32-a2af-a1bfe113a9b0)

# Окружение. 
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by rinat-yar** [comment]
https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/blob/32766f9979e60837634d7f91332a2b765b8cfa4c/src/main/java/ru/netology/CreditAccount.java#L86-L92
