### ISSUE TITLE
При создании счета баланс больше кредитного лимита.

### ISSUE THREAD

**Issue by YackovPetrov** [rinat-yar/Team_project_on_the_Java_course_for_testers#5]
# Описание.
Если создать счет в котором баланс больше кредитного лимита, то он создается.

# Локация дефекта.

https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/blob/bbbc026a1d5326a69e9765a4b6b8ea2e6efa3a9f/src/main/java/ru/netology/CreditAccount.java#L20

# Шаги воспроизведения.
1. Открыть [командный проект](https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers) в IDEA
2. Создать тест в CreditAccountTest для конструктора CreditAccount в классе CreditAccount
3. Выставить значение переменной initialBalance: 6_000
4. Выставить значение переменной creditLimit: 5_000
5. Выставить значение переменной rate: 15
6. Провести проверку ожидаемого результата с актуальным
7. Посмотреть на выводы в консоли.

*Ожидаемый результат:* Баланс не может быть больше кредитного класса.
*Фактический результат:* Баланс больше кредитного класса.

# Скриншот.

![image](https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/assets/128886262/735615e3-11c9-4cff-83d9-6b5caa7e66d7)

# Окружение. 
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by rinat-yar** [comment]
https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/blob/32766f9979e60837634d7f91332a2b765b8cfa4c/src/main/java/ru/netology/CreditAccount.java#L22-L40
