### ISSUE TITLE
Создается счет с отрицательным кредитным лимитом.

### ISSUE THREAD

**Issue by YackovPetrov** [rinat-yar/Team_project_on_the_Java_course_for_testers#6]
# Описание.
Если создать счет в классе CreditAccount, в котором кредитный лимит отрицательный, то он создается.

# Локация дефекта.

https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/blob/bbbc026a1d5326a69e9765a4b6b8ea2e6efa3a9f/src/main/java/ru/netology/CreditAccount.java#L20

# Шаги воспроизведения.
1. Открыть [командный проект](https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers) в IDEA
2. Создать тест в CreditAccountTest для конструктора CreditAccount
3. Выставить значение переменной initialBalance: 5_000
4. Выставить значение переменной creditLimit: -5_000
5. Выставить значение переменной rate: 15
6. Провести проверку ожидаемого результата с актуальным
7. Посмотреть на выводы в консоли.

*Ожидаемый результат:* java.lang.IllegalArgumentException: Кредитный счет не может быть отрицательным, а у вас: -5_000
*Фактический результат:* org.opentest4j.AssertionFailedError: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown, счет создается.

# Скриншот.

![image](https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/assets/128886262/91dcb096-c298-4bcb-965c-ea26d1a7b8c3)

# Окружение. 
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by rinat-yar** [comment]
https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/blob/32766f9979e60837634d7f91332a2b765b8cfa4c/src/main/java/ru/netology/CreditAccount.java#L22-L40
