### ISSUE TITLE
При оплате списание не происходит.

### ISSUE THREAD

**Issue by YackovPetrov** [rinat-yar/Team_project_on_the_Java_course_for_testers#7]
# Описание.
При оплате со счета CreditAccount баланс показывает отрицательное значение на сумму оплаты.

# Локация дефекта.

https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/blob/bbbc026a1d5326a69e9765a4b6b8ea2e6efa3a9f/src/main/java/ru/netology/CreditAccount.java#L41

# Шаги воспроизведения.
1. Открыть [командный проект](https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers) в IDEA
2. Создать тест в CreditAccountTest для метода Pay в классе CreditAccount
3. Выставить значение переменной initialBalance: 3_000
4. Выставить значение переменной creditLimit: 5_000
5. Выставить значение переменной rate: 15
6. Вызвать метод pay.
7. Провести проверку ожидаемого результата с актуальным
8. Посмотреть на выводы в консоли.

*Ожидаемый результат:* На счете останется 2_000.
*Фактический результат:* На счете остается -1_000.

# Скриншот.

![image](https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/assets/128886262/23ab9433-476a-4243-90d6-024f5db39267)

# Окружение. 
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by rinat-yar** [comment]
https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/blob/32766f9979e60837634d7f91332a2b765b8cfa4c/src/main/java/ru/netology/CreditAccount.java#L58-L71
