### ISSUE TITLE
Счёт не уменьшается при совершении покупки после достижения минимального значения

### ISSUE THREAD

**Issue by rinat-yar** [rinat-yar/Team_project_on_the_Java_course_for_testers#9]
# Локация дефекта
https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/blob/bbbc026a1d5326a69e9765a4b6b8ea2e6efa3a9f/src/main/java/ru/netology/SavingAccount.java#L49
 
# Шаги воспроизведения
Открыть [код программы](https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/blob/main/src/test/java/ru/netology/test/SavingAccountTest.java) в IDEA
Выбрать тест "testPayMinBalance"
Вставить значения переменной initialBalance 2000
Вставить значения переменной minBalance 1000
Вставить значения переменной maxBalance 10000
Вставить значения переменной rate 5
Ввести сумму пополнения account.add(1_000)
Запустить программу
Посмотреть на вывод в консоли

Ожидаемый результат: метод pay возвращает true равная 1000
Фактический результат: метод pay возвращает false

# Скриншот

![image](https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/assets/127385270/4fbae856-805e-4a0f-afd6-a13f19c79a43)

# Окружение
Операционная система: Windows 10 pro
IDE: IntelliJ IDEA 2023.1 (версия для сообщества)
Java: OpenJDK 11

**Comment by YackovPetrov** [comment]
Внесены изменения в метод pay.
https://github.com/rinat-yar/Team_project_on_the_Java_course_for_testers/blob/32766f9979e60837634d7f91332a2b765b8cfa4c/src/main/java/ru/netology/SavingAccount.java#L71
